config/routes.rb
Rails.application.routes.draw do
  root to: 'homes#top'
  # 管理者用
# URL /admin/sign_in ...
devise_for :admin, skip: [:registrations, :passwords], controllers: {
  registrations: "admin/registrations",
  sessions: 'admin/sessions'
}
namespace :admin do
 resources :quizzes,only:[:new,:create,:destroy,:edit,:update] do
   resources :questions,only:[:new,:create,:edit,:update,:destroy] do
     resources :choices,only:[:new,:create,:edit,:update,:show]
     resources :vest_answers,only:[:create,:edit,:update,:destroy]
   end
 end
 resources :requests,only:[:index,:show,:update]
end

devise_for :customers, skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

namespace :public do
 resource :customers,only:[:show,:edit,:update,:destroy]
 get "customers/detail",to: 'customers#detail',as:"detail"
 resources :quizzes,only:[:index] do
  resources :questions,only:[:show]
  resources :answers,only:[:create]
  get "result",to: 'answers#result',as:"result"
 end
 resources :requests,only:[:new,:create,:show,:destroy]
end

devise_scope :customer do
  post 'customers/guest_sign_in', to: 'customers/sessions#guest_sign_in'
end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to:quiz
  belongs_to:customer
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/choice.rb
class Choice < ApplicationRecord
  belongs_to:question

  validates :body,presence: :true

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many:answers,dependent: :destroy
  has_many:requests,dependent: :destroy
  validates :name,presence: :true

  def self.guest
    find_or_create_by!(name: 'guestuser' ,email: 'guest@example.com') do |customer|
      customer.password = SecureRandom.urlsafe_base64
      customer.name = "guestuser"
    end
  end

end

app/models/form.rb
module Form
  def self.table_name_prefix
    'form_'
  end
end

app/models/form/base.rb
class Form::Base
  include ActiveModel::Model
  include ActiveModel::Callbacks
  include ActiveModel::Validations
  include ActiveModel::Validations::Callbacks
end

app/models/form/choice_collection.rb
class Form::ChoiceCollection < Form::Base
  FORM_COUNT = 3
  attr_accessor :choices

# 　newアクションのnewでは()内は空。createアクションのnewでchoice_collection_paramsの値が引数で入る
  def initialize(attributes = {},final_answer = 0)
    super attributes
    self.choices = FORM_COUNT.times.map { Choice.new() } unless self.choices.present?
    unless final_answer == nil
      self.choices[final_answer.to_i - 1].answer = true unless final_answer == 0
    end
  end

  # # 上でsuper attributesとしているので必要
  def choices_attributes=(attributes)
    self.choices = attributes.map { |_, v|Choice.new(v) }
  end

  def save
  # 複数件全て保存できた場合のみ実行したいので、transactionを使用する
    Choice.transaction do
      if self.choices.pluck(:answer).count(true) != 1
        return false
      end
      self.choices.map(&:save!)
    end
  rescue
      return false
  else
  #     # validates :description, presence: :trueに引っ掛かったら、resucue節でロールバックさせる
      return true
  end
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to:quiz
  has_many:choices,dependent: :destroy
  has_one_attached :image
  has_one :vest_answer

  validates :body, presence: :true

end

app/models/quiz.rb
class Quiz < ApplicationRecord
  has_many:questions,dependent: :destroy
  has_many:answers,dependent: :destroy

  validates :name,presence: true

end

app/models/request.rb
class Request < ApplicationRecord
  belongs_to:customer
  validates :title,presence: true
  validates :content,presence: true

  enum status: {wait: 0,support: 1,complete: 2}
end

app/models/vest_answer.rb
class VestAnswer < ApplicationRecord
  belongs_to:question

  validates :description,presence: :true
end

app/controllers/admin/quizzes_controller.rb
class Admin::QuizzesController < ApplicationController
  before_action :move_to_signed_in

  def new
    @quiz = Quiz.new
    @private_quizs = Quiz.where(status: false)
    @public_quizs = Quiz.where(status: true)
  end

  def create
    @quiz = Quiz.new(quiz_params)
    if @quiz.save
      redirect_to new_admin_quiz_path
    else
      flash[:danger] = @quiz.errors.full_messages
      redirect_to new_admin_quiz_path
    end
  end

  def destroy
    quiz = Quiz.find(params[:id])
    quiz.destroy
    redirect_to new_admin_quiz_path
  end

  def edit
    @quiz = Quiz.find(params[:id])
  end

  def update
    @quiz = Quiz.find(params[:id])
    if @quiz.questions.select{|n| n.choices != []}.count == 10
      if @quiz.update(quiz_params)
        redirect_to new_admin_quiz_question_path(@quiz.id)
      else
        flash[:danger] = @quiz.errors.full_messages
        redirect_to edit_admin_quiz_path(@quiz.id)
      end
    else
      if @quiz.update(name: params[:quiz][:name])
        flash[:danger] = "※公開するには問題を１０個作成してください"
        redirect_to new_admin_quiz_question_path(@quiz.id)
      else
        flash[:danger] = @quiz.errors.full_messages
        redirect_to edit_admin_quiz_path(@quiz.id)
      end
    end
  end

  private

  def quiz_params
    params.require(:quiz).permit(:name,:status)
  end

  def move_to_signed_in
    unless admin_signed_in?
      # サインインしていないユーザーはログインページが表示される
      redirect_to new_admin_session_path, notice: '管理者としてログインしてください！'
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/helpers/admin/choices_helper.rb
module Admin::ChoicesHelper
end

app/helpers/admin/questions_helper.rb
module Admin::QuestionsHelper
end

app/helpers/admin/quizzes_helper.rb
module Admin::QuizzesHelper
end

app/helpers/admin/requests_helper.rb
module Admin::RequestsHelper
end

app/helpers/admin/vest_answers_helper.rb
module Admin::VestAnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/admin/quizzes/edit.html.erb
<div class="main">
  <div class="container">
    <div class="row">
      <div class="col text-center quiz_show">
        <h1>クイズ編集画面</h1>
        <% flash.each do |message_type, messages| %>
          <% if messages.class == Array %>
            <% messages.each do |message| %>
              <div class="alert alert-<%= message_type %>"><%= message %></div>
            <% end %>
          <% else %>
            <div class="alert alert-danger"><%= messages %></div>
          <% end %>
        <% end %>
        <%= form_with model: @quiz,url: admin_quiz_path(@quiz.id),method: :patch do |f| %>
          <%= f.text_field :name,class:"form-control" %>
          <%= f.radio_button :status, :true %>
          <%= f.label :status, "公開", {value: :true, style: "display: inline-block;"} %>
          <%= f.radio_button :status, :false %>
          <%= f.label :status, "非公開", {value: :false, style: "display: inline-block;"} %><br>
          <%= f.submit"変更",class:"btn btn-success mb-5" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/admin/quizzes/new.html.erb
<div class="main">
  <div class="container">

    <div class="row mb-3">
      <div class="col text-center">
        <h1 class="quiz_show mt-3 mb-3">クイズ内容投稿</h1>

        <% flash.each do |message_type, messages| %>
            <% if messages.class == Array %>
              <% messages.each do |message| %>
                <div class="alert alert-<%= message_type %>"><%= message %></div>
              <% end %>
            <% else %>
                <div class="alert alert-success"><%= messages %></div>
            <% end %>
        <% end %>

        <%= form_with model: @quiz,url: admin_quizzes_path do |f| %>
          <label class="text-white">クイズの種類</label><br>
           <%= f.text_field :name,placeholder:"クイズの太枠",class:"form-control" %><br>
          <%= f.submit"送信",class:"btn btn-success" %><br>
        <% end %>
      </div>
    </div>
    <h2 class="quiz_show mt-3 mb-3 text-center">公開中</h2>
    <div class="row">
      <div class="col quiz_container">
        <% @public_quizs.each do |list| %>
          <%= link_to new_admin_quiz_question_path(list.id) do %>
            <div class="rounded quiz_title"><%= list.name %></div>
          <% end %>
        <% end %>
      </div>
    </div>
    <h2 class="quiz_show mt-3 mb-3 text-center">非公開</h2>
    <div class="row">
      <div class="col quiz_container">
        <% @private_quizs.each do |list| %>
          <%= link_to new_admin_quiz_question_path(list.id) do %>
            <div class="rounded quiz_title"><%= list.name %></div>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>