config/routes.rb
Rails.application.routes.draw do
  root to: 'homes#top'
  # 管理者用
# URL /admin/sign_in ...
devise_for :admin, skip: [:registrations, :passwords], controllers: {
  registrations: "admin/registrations",
  sessions: 'admin/sessions'
}
namespace :admin do
 resources :quizzes,only:[:new,:create,:destroy,:edit,:update] do
   resources :questions,only:[:new,:create,:edit,:update,:destroy] do
     resources :choices,only:[:new,:create,:edit,:update,:show]
     resources :vest_answers,only:[:create,:edit,:update,:destroy]
   end
 end
 resources :requests,only:[:index,:show,:update]
end

devise_for :customers, skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

namespace :public do
 resource :customers,only:[:show,:edit,:update,:destroy]
 get "customers/detail",to: 'customers#detail',as:"detail"
 resources :quizzes,only:[:index] do
  resources :questions,only:[:show]
  resources :answers,only:[:create]
  get "result",to: 'answers#result',as:"result"
 end
 resources :requests,only:[:new,:create,:show,:destroy]
end

devise_scope :customer do
  post 'customers/guest_sign_in', to: 'customers/sessions#guest_sign_in'
end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to:quiz
  belongs_to:customer
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/choice.rb
class Choice < ApplicationRecord
  belongs_to:question

  validates :body,presence: :true

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many:answers,dependent: :destroy
  has_many:requests,dependent: :destroy
  validates :name,presence: :true

  def self.guest
    find_or_create_by!(name: 'guestuser' ,email: 'guest@example.com') do |customer|
      customer.password = SecureRandom.urlsafe_base64
      customer.name = "guestuser"
    end
  end

end

app/models/form.rb
module Form
  def self.table_name_prefix
    'form_'
  end
end

app/models/form/base.rb
class Form::Base
  include ActiveModel::Model
  include ActiveModel::Callbacks
  include ActiveModel::Validations
  include ActiveModel::Validations::Callbacks
end

app/models/form/choice_collection.rb
class Form::ChoiceCollection < Form::Base
  FORM_COUNT = 3
  attr_accessor :choices

# 　newアクションのnewでは()内は空。createアクションのnewでchoice_collection_paramsの値が引数で入る
  def initialize(attributes = {},final_answer = 0)
    super attributes
    self.choices = FORM_COUNT.times.map { Choice.new() } unless self.choices.present?
    unless final_answer == nil
      self.choices[final_answer.to_i - 1].answer = true unless final_answer == 0
    end
  end

  # # 上でsuper attributesとしているので必要
  def choices_attributes=(attributes)
    self.choices = attributes.map { |_, v|Choice.new(v) }
  end

  def save
  # 複数件全て保存できた場合のみ実行したいので、transactionを使用する
    Choice.transaction do
      if self.choices.pluck(:answer).count(true) != 1
        return false
      end
      self.choices.map(&:save!)
    end
  rescue
      return false
  else
  #     # validates :description, presence: :trueに引っ掛かったら、resucue節でロールバックさせる
      return true
  end
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to:quiz
  has_many:choices,dependent: :destroy
  has_one_attached :image
  has_one :vest_answer

  validates :body, presence: :true

end

app/models/quiz.rb
class Quiz < ApplicationRecord
  has_many:questions,dependent: :destroy
  has_many:answers,dependent: :destroy

  validates :name,presence: true

end

app/models/request.rb
class Request < ApplicationRecord
  belongs_to:customer
  validates :title,presence: true
  validates :content,presence: true

  enum status: {wait: 0,support: 1,complete: 2}
end

app/models/vest_answer.rb
class VestAnswer < ApplicationRecord
  belongs_to:question

  validates :description,presence: :true
end

app/controllers/admin/choices_controller.rb
class Admin::ChoicesController < ApplicationController
  # before_action :if_not_admin
  def new
    @quiz = Quiz.find(params[:quiz_id])
    @question = Question.find(params[:question_id])
    @form = Form::ChoiceCollection.new
    @questions = @question.choices
  end

  def show
    @question = Question.find(params[:question_id])
    @quiz = Quiz.find(params[:quiz_id])
    choices = params[:id]
    choices = choices.split("/")
    @first_choice = Choice.find(choices[0].to_i)
    @second_choice = Choice.find(choices[1].to_i)
    @third_choice = Choice.find(choices[2].to_i)
    @vest_answer = VestAnswer.new
  end

  def create
    final_answer = params[:form_choice_collection][:answer]
    @quiz = Quiz.find(params[:quiz_id])
    @question = Question.find(params[:question_id])
    @form = Form::ChoiceCollection.new(choice_collection_params,final_answer)
    if @form.save
      redirect_to admin_quiz_question_choice_path(@quiz.id,@question.id,@question.choices.ids)
    else
      flash.now[:danger] = "解答は３件全て記入してください(正解は一つのみ(チェックは一つ))"
      render :new
    end
  end

  def edit
    @question = Question.find(params[:question_id])
    @quiz = Quiz.find(params[:quiz_id])
    @choice = Choice.find(params[:id])
  end

  def update
    @question = Question.find(params[:question_id])
    @quiz = Quiz.find(params[:quiz_id])
    choice = Choice.find(params[:id])
    choice.update(choice_params)
    redirect_to admin_quiz_question_choice_path(@quiz.id,@question.id,@question.choices.ids)
  end

  private

  def choice_collection_params
    params.require(:form_choice_collection).permit(choices_attributes: [:body,:question_id])
  end

  def choice_params
    params.require(:choice).permit(:body)
  end

end

app/controllers/admin/requests_controller.rb
class Admin::RequestsController < ApplicationController
  def index
    @post_request = Request.all
  end
  def show
    @post_request = Request.find(params[:id])
  end

  def update
    post_request = Request.find(params[:id])
    post_request.update(post_request_params)
    redirect_to request.referer
  end

  private
  def post_request_params
    params.require(:request).permit(:status)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/helpers/admin/choices_helper.rb
module Admin::ChoicesHelper
end

app/helpers/admin/questions_helper.rb
module Admin::QuestionsHelper
end

app/helpers/admin/quizzes_helper.rb
module Admin::QuizzesHelper
end

app/helpers/admin/requests_helper.rb
module Admin::RequestsHelper
end

app/helpers/admin/vest_answers_helper.rb
module Admin::VestAnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/admin/requests/index.html.erb
<div class="main">
  <div class="container">
    <h1 class="quiz_show">ユーザーからのリクエスト一覧</h1>
    <table class="table quiz_show text-center">
      <tr>
        <th style="width:5%"></th>
        <th style="width:20%">投稿者</th>
        <th style="width:25%">タイトル</th>
        <th style="width:40%">コンテンツ</th>
        <th style="width:10%">状況</th>
      </tr>
      <% @post_request.each_with_index do |list, i| %>
        <tr>
          <td><%= i+1 %></td>
          <td><%= list.customer.name %></td>
          <td>
            <%= link_to admin_request_path(list.id) do %>
              <%= list.title %>
            <% end %>
          </td>
          <td><%= list.content %></td>
          <td><%= list.status_i18n %></td>
        </tr>
      <% end %>
    </table>
  </div>
</div>

app/views/admin/requests/show.html.erb
<div class="main">
  <div class="container text-center">
    <h1 class="quiz_show">リクエスト詳細(<span class="text-danger"><%= @post_request.status_i18n %></span>)</h1>
    <div class="row quiz_show">
      <div class="col-4">
        <h2>タイトル</h2>
        <div style="height:50vh;" class="d-flex align-items-center justify-content-center">
          <p><%= @post_request.title %></p>
        </div>
      </div>
      <div class="col-6">
        <h2>詳細</h2>
        <div style="height:50vh;" class="d-flex align-items-center justify-content-center">
          <p><%= @post_request.content %></p>
        </div>
      </div>
      <div class="col-2">
        <h2>状況</h2>
        <div style="height:50vh;" class="d-flex align-items-center justify-content-center">
          <%= form_with model: @post_request,url: admin_request_path(@post_request.id) do |f| %>
            <%= f.select :status, Request.statuses.keys.map {|k| [I18n.t("enums.request.status.#{k}"), k]} %>
            <%= f.submit"変更",class:"btn btn-success" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>