config/routes.rb
Rails.application.routes.draw do
  root to: 'homes#top'
  # 管理者用
# URL /admin/sign_in ...
devise_for :admin, skip: [:registrations, :passwords], controllers: {
  registrations: "admin/registrations",
  sessions: 'admin/sessions'
}
namespace :admin do
 resources :quizzes,only:[:new,:create,:destroy,:edit,:update] do
   resources :questions,only:[:new,:create,:edit,:update,:destroy] do
     resources :choices,only:[:new,:create,:edit,:update,:show]
     resources :vest_answers,only:[:create,:edit,:update,:destroy]
   end
 end
 resources :requests,only:[:index,:show,:update]
end

devise_for :customers, skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

namespace :public do
 resource :customers,only:[:show,:edit,:update,:destroy]
 get "customers/detail",to: 'customers#detail',as:"detail"
 resources :quizzes,only:[:index] do
  resources :questions,only:[:show]
  resources :answers,only:[:create]
  get "result",to: 'answers#result',as:"result"
 end
 resources :requests,only:[:new,:create,:show,:destroy]
end

devise_scope :customer do
  post 'customers/guest_sign_in', to: 'customers/sessions#guest_sign_in'
end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to:quiz
  belongs_to:customer
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/choice.rb
class Choice < ApplicationRecord
  belongs_to:question

  validates :body,presence: :true

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many:answers,dependent: :destroy
  has_many:requests,dependent: :destroy
  validates :name,presence: :true

  def self.guest
    find_or_create_by!(name: 'guestuser' ,email: 'guest@example.com') do |customer|
      customer.password = SecureRandom.urlsafe_base64
      customer.name = "guestuser"
    end
  end

end

app/models/form.rb
module Form
  def self.table_name_prefix
    'form_'
  end
end

app/models/form/base.rb
class Form::Base
  include ActiveModel::Model
  include ActiveModel::Callbacks
  include ActiveModel::Validations
  include ActiveModel::Validations::Callbacks
end

app/models/form/choice_collection.rb
class Form::ChoiceCollection < Form::Base
  FORM_COUNT = 3
  attr_accessor :choices

# 　newアクションのnewでは()内は空。createアクションのnewでchoice_collection_paramsの値が引数で入る
  def initialize(attributes = {},final_answer = 0)
    super attributes
    self.choices = FORM_COUNT.times.map { Choice.new() } unless self.choices.present?
    unless final_answer == nil
      self.choices[final_answer.to_i - 1].answer = true unless final_answer == 0
    end
  end

  # # 上でsuper attributesとしているので必要
  def choices_attributes=(attributes)
    self.choices = attributes.map { |_, v|Choice.new(v) }
  end

  def save
  # 複数件全て保存できた場合のみ実行したいので、transactionを使用する
    Choice.transaction do
      if self.choices.pluck(:answer).count(true) != 1
        return false
      end
      self.choices.map(&:save!)
    end
  rescue
      return false
  else
  #     # validates :description, presence: :trueに引っ掛かったら、resucue節でロールバックさせる
      return true
  end
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to:quiz
  has_many:choices,dependent: :destroy
  has_one_attached :image
  has_one :vest_answer

  validates :body, presence: :true

end

app/models/quiz.rb
class Quiz < ApplicationRecord
  has_many:questions,dependent: :destroy
  has_many:answers,dependent: :destroy

  validates :name,presence: true

end

app/models/request.rb
class Request < ApplicationRecord
  belongs_to:customer
  validates :title,presence: true
  validates :content,presence: true

  enum status: {wait: 0,support: 1,complete: 2}
end

app/models/vest_answer.rb
class VestAnswer < ApplicationRecord
  belongs_to:question

  validates :description,presence: :true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/helpers/admin/choices_helper.rb
module Admin::ChoicesHelper
end

app/helpers/admin/questions_helper.rb
module Admin::QuestionsHelper
end

app/helpers/admin/quizzes_helper.rb
module Admin::QuizzesHelper
end

app/helpers/admin/requests_helper.rb
module Admin::RequestsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>

app/views/layouts/_error.html.erb
<% if model.errors.any? %>
  <div class="alert alert-warning">
    <ul>
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ruby</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light fixed-top header-nav" >
      <%= link_to root_path,class:"navbar-brand" do %>
        <%= image_tag "logo.png",size:"300x40" %>
      <% end %>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
              <ul class="navbar-nav ml-auto text-center">
                <% if customer_signed_in? %>
                  <li class="nav-item active mr-2" id = "reload_of_1"><%= link_to destroy_customer_session_path,method: :delete, class:"nav-link active menu-list" do %><i class="fas fa-sign-out-alt fa-fw"></i><br>ログアウト<% end %></li>
                  <li class="nav-item mr-2" id = "reload_of_2"><%= link_to public_quizzes_path, class:"nav-link" do %><i class="fas fa-plus fa-fw"></i><br>クイズ一覧<% end %></li>
                  <li class="nav-item mr-2" id = "reload_of_3"><%= link_to public_customers_path, class:"nav-link active menu-list" do %><i class="fas fa-parking fa-fw"></i><br>マイページ<% end %></li>
                  <li class="nav-item mr-2" id = "reload_of_4"><%= link_to new_public_request_path, class:"nav-link active menu-list" do %><i class="fas fa-parking fa-fw"></i><br>リクエスト枠<% end %></li>
                <% end %>
                <% unless customer_signed_in? %>
                  <% unless  admin_signed_in? %>
                   <li class="nav-item mr-2"><%= link_to public_quizzes_path, class:"nav-link" do %><i class="fas fa-sign-in-alt fa-fw"></i></i><br>クイズ一覧<% end %></li>
                   <li class="nav-item mr-2"><%= link_to new_admin_session_path, class:"nav-link" do %><i class="fas fa-sign-in-alt fa-fw"></i><br>管理者ログイン<% end %></li>
                   <li class="nav-item mr-2"><%= link_to new_customer_registration_path, class:"nav-link" do %><i class="fas fa-parking fa-fw"></i><br>新規登録<% end %></li>
                   <li class="nav-item"><%= link_to new_customer_session_path, class:"nav-link" do %><i class="fas fa-user fa-fw"></i><br>ログイン<% end %></li>
                   <li class="nav-item"><%= link_to customers_guest_sign_in_path, class: "nav-link", method: :post do %><i class="fas fa-user fa-fw"></i><br>ゲストログイン<% end %></li>

                  <% end %>
                <% end %>
                <% if admin_signed_in? %>
                  <li class="nav-item mr-2"><%= link_to destroy_admin_session_path,method: :delete, class:"nav-link" do %><i class="fas fa-user fa-fw"></i><br>管理者ログアウト<% end %></li>
                  <li class="nav-item mr-2"><%= link_to new_admin_quiz_path, class:"nav-link" do %><i class="fas fa-parking fa-fw"></i><br>クイズ投稿<% end %></li>
                  <li class="nav-item mr-2"><%= link_to admin_requests_path, class:"nav-link active menu-list" do %><i class="fas fa-parking fa-fw"></i><br>リクエスト枠<% end %></li>
                <% end %>
              </ul>
      </div>
    </nav>





    <%= yield %>
    <footer>
        <div class='pb-3 pt-2'>
      	   <div class='mx-auto'>
          		<div class="text-center">
          		  <i class="fab fa-twitter mr-3 fa-2x"></i>
            		<i class="fab fa-facebook mr-3 fa-2x"></i>
            		<i class="fab fa-instagram mr-3 fa-2x"></i>
          		</div>
          		<div class="mt-1 text-center">
          		  <p><i class="fas fa-phone fa-fw"></i>xxx-xxxx-xxx</p>
            	  <p><i class="fas fa-location-arrow fa-fw"></i>〇〇県〇〇市〇〇町〇丁目</p>
              	<p><i class="fas fa-envelope fa-fw"></i>portofollio@mail.com</p>
          	  </div>
            </div>
        </div>
    </footer>

  </body>
</html>